### ISSUE TITLE
MI Fluid pipes crashing server?

### ISSUE THREAD

**Issue by Sh1tL0rd** [TeamAOF/All-of-Fabric-6#347]
im pretty sure MI pipes in my base are crashing the server? can someone interpret this crash log pls :)
[crash-2023-08-06_07.31.48-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/12268889/crash-2023-08-06_07.31.48-server.txt)

**Comment by Linguardium** [comment]
> Description: Watching Server

This mean "server froze and stopped responding so minecraft killed it"

```
	at net.zestyblaze.lootr.blocks.entities.LootrChestBlockEntity.unpackLootTable(LootrChestBlockEntity.java:249)
	at net.zestyblaze.lootr.util.ChestUtil$$Lambda$33400/0x00000008046d8680.unpackLootTable(Unknown Source)
	at net.zestyblaze.lootr.data.ChestData.createInventory(ChestData.java:217)
	at net.zestyblaze.lootr.data.DataStorage.getInventory(DataStorage.java:194)
	at net.zestyblaze.lootr.util.ChestUtil.handleLootChest(ChestUtil.java:115)
	at net.zestyblaze.lootr.blocks.LootrChestBlock.method_9534(LootrChestBlock.java:61)
```
cery clearly not caused by MI pipes. this is someone opening a lootr chest. its doing a structure lookup to find a structure for a map. This is a known vanilla minecraft issue. increase max-tick-time to 240000 or so and it should be a bit better. if that doesnt resolve it, it could be your server doesnt have the resources to do the lookup, you should look into pregenerating your world as well
