### ISSUE TITLE
AOF 6 Server crashing

### ISSUE THREAD

**Issue by Lucas-S-Vieira** [TeamAOF/All-of-Fabric-6#383]
I've created a server for me and my friends and we are having an issue, when one of the players enter some kinda of portal, i dunno from what mod it is, the server crashes

Edit: It's a portal from Mine Cells

Crash report:
[crash-2023-09-12_20.22.36-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/12591678/crash-2023-09-12_20.22.36-server.txt)
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/116003800/b04a6da2-a7e1-45b2-a434-b49d9ee9038c)

**Comment by Linguardium** [comment]
`java.lang.Error: Watchdog`

This means your server took too long to process something

```
Thread: Server Watchdog
Stacktrace:
	at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at net.minecraft.class_1255.method_20813(class_1255.java:152)
	at net.minecraft.class_1255.method_18857(class_1255.java:142)
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1781)
```

Looks like it was generating chunks

further down we see the real problem:

```


"Worker-Main-22" daemon prio=5 Id=108 RUNNABLE
	at com.mojang.datafixers.kinds.Applicative.ap2(Applicative.java:76)
	at com.mojang.datafixers.optics.ListTraversal.lambda$wander$0(ListTraversal.java:19)
	at com.mojang.datafixers.optics.ListTraversal$$Lambda$29658/0x000002464d48f280.apply(Unknown Source)
	at com.mojang.datafixers.FunctionType$Instance.lambda$wander$4(FunctionType.java:94)
	at com.mojang.datafixers.FunctionType$Instance$$Lambda$29652/0x000002464d48dd70.apply(Unknown Source)
	at com.mojang.datafixers.FunctionType$$Lambda$29642/0x000002464d48c6c0.apply(Unknown Source)
	at com.mojang.datafixers.util.Either.lambda$mapRight$1(Either.java:166)
	at com.mojang.datafixers.util.Either$$Lambda$17058/0x000002464c05af80.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
	at com.mojang.datafixers.util.Either.mapRight(Either.java:166)
	at com.mojang.datafixers.FunctionType$Instance.lambda$right$6(FunctionType.java:104)
	at com.mojang.datafixers.FunctionType$Instance$$Lambda$29649/0x000002464d48d6b0.apply(Unknown Source)
	at com.mojang.datafixers.FunctionType$$Lambda$29642/0x000002464d48c6c0.apply(Unknown Source)
	at java.base@17.0.8/java.util.function.Function.lambda$compose$0(Function.java:68)
	at java.base@17.0.8/java.util.function.Function$$Lambda$18451/0x000002464c1e0d58.apply(Unknown Source)
	at java.base@17.0.8/java.util.function.Function.lambda$compose$0(Function.java:68)
	at java.base@17.0.8/java.util.function.Function$$Lambda$18451/0x000002464c1e0d58.apply(Unknown Source)
	at com.mojang.datafixers.FunctionType$$Lambda$29642/0x000002464d48c6c0.apply(Unknown Source)
	at com.mojang.datafixers.FunctionType$Instance.lambda$first$1(FunctionType.java:81)
```

outdated mod structures...
Since modernfix is in the pack, turn off the watchdog timer by setting max-tick-time in server.properties to 0. once done, it will likely disconnect you next time you enter the mine cells portal but it should finish updating the data for the structure and modernfix will cache it. then you shouldnt run into this problem with this specific structure agian. sadly there are 2400 outdated structures in this pack...so if you didnt pregenerate your world, you are going to have a bad time.

**Comment by Linguardium** [comment]
also, you appear to be playing an older version of the pack without modernfix...if you dont plan to update your pack regularly, install modernfix https://www.curseforge.com/minecraft/mc-mods/modernfix/files/4728402

**Comment by Lucas-S-Vieira** [comment]
Thanks, i'm gonna try to do it

**Comment by Lucas-S-Vieira** [comment]
> also, you appear to be playing an older version of the pack without modernfix...if you dont plan to update your pack regularly, install modernfix https://www.curseforge.com/minecraft/mc-mods/modernfix/files/4728402

To install this, all my players need to install it to?

**Comment by Linguardium** [comment]
nope, it should work serverside only, but i would recommend they do as it reduces load time and memory usage, even in vanilla

**Comment by Linguardium** [comment]
It might be worth it to post the log to a place like https://mclo.gs/ and then link it here.

**Comment by Lucas-S-Vieira** [comment]
> It might be worth it to post the log to a place like https://mclo.gs/ and then link it here.

ok, thanks

**Comment by Lucas-S-Vieira** [comment]
https://mclo.gs/jfwXzrd

**Comment by Linguardium** [comment]
are you intentionally using ipv6?

**Comment by Lucas-S-Vieira** [comment]
> are you intentionally using ipv6?
> 
> edit: I installed a fresh 1.8.2 version and added the same modernfix release to it, set it to an offline server, and cant reproduce the issue you are having. everything appears to be running fine. I do force ipv4 on my computer, and i notice yours is using ipv6 but i dont know what your server is doing in regards to networking.

I'm gonna try to force the use of ipv4

**Comment by Lucas-S-Vieira** [comment]
I forced my pc to use ipv4, im openning the server yer, but this is my server config:

#Minecraft server properties
#Tue Sep 12 22:41:04 BRT 2023
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=hard
network-compression-threshold=256
max-tick-time=0
require-resource-pack=false
use-native-transport=true
max-players=12
online-mode=false
enable-status=true
allow-flight=true
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
previews-chat=false
spawn-animals=true
function-permission-level=2
level-type=minecraft\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984

**Comment by Lucas-S-Vieira** [comment]
> are you intentionally using ipv6?
> 
> edit: I installed a fresh 1.8.2 version and added the same modernfix release to it, set it to an offline server, and cant reproduce the issue you are having. everything appears to be running fine. I do force ipv4 on my computer, and i notice yours is using ipv6 but i dont know what your server is doing in regards to networking.

What java jdk you're using?

**Comment by Lucas-S-Vieira** [comment]
I've deleted the servestarter.lock to force the mods to be re-installed, seems to work now, apparently
I'm gonna test along the day and if the errors appear again, i update in here

**Comment by Lucas-S-Vieira** [comment]
So, im gonna close this, cause my issue is another, thanks for the help
